### PR TITLE
Added danish language

### PR DESCRIPTION
**Pull request by AlbertCoolGuy**
Just changed what made sense. Sorry if it doesn't work.

### CODE REVIEW

**Comment by geniiii** [comment]
You seem to have forgotten to bump the language count. Past that, it seems fine and should hopefully work.

**Comment by AlbertCoolGuy** [comment]
Where did I miss it?

**Comment by geniiii** [comment]
I've opened a PR (https://github.com/AlbertCoolGuy/3DStris/pull/1) that uses the famfamfam flag icon for Denmark. This should also fix the build.

**Comment by AlbertCoolGuy** [comment]
Have you tried building?

**Comment by AlbertCoolGuy** [comment]
Can you build it for me? I can't get it to work.

**Comment by geniiii** [comment]
> 
> 
> Can you build it for me? I can't get it to work.

There are automated Azure Pipelines builds (https://github.com/3DStris/3DStris/runs/533560953, for example), however there seem to be unrelated to this PR issues that need to be fixed before I can merge.

**Comment by AlbertCoolGuy** [comment]
I get a "Translation - Abort" error when running the program

**Comment by AlbertCoolGuy** [comment]
Can you credit me in the readme?

**Comment by geniiii** [comment]
> 
> 
> Can you credit me in the readme?

41dfed405864ac8a68e70c8a5b57c08b3d41da29 👍

**Comment by AlbertCoolGuy** [comment]
Thanks! :smile:

**Pull request merged**
