### PR TITLE
Japanese translation

### PR DESCRIPTION
**Pull request by Epicpkmn11**
Saw this and couldn't resist some Tetris ;P
Its fine if you don't want it but I figured I'd translate to Japanese since I could, let me know if you need me to change anything.

Tested on my n3DS (U) and everything seems to be working fine except the language list going a bit off screen.

### CODE REVIEW

**Comment by geniiii** [comment]
Thank you! I'll merge tomorrow (2am here) and see what I can do about the language list afterwards.

**Comment by geniiii** [comment]
You can get flag icons from here: http://www.famfamfam.com/lab/icons/flags/
I should probably add it to the README.

**Comment by Epicpkmn11** [comment]
Ah, I just used the GBAtemp one since the others looked the same as those, I guess that's where GBAtemp got them from since their identical lol

**Comment by geniiii** [comment]
I've changed the menu design to one that can allow more buttons to fit on the screen, should work correctly now.

**Pull request merged**
